### ISSUE TITLE
rename elbe XML namespace

### ISSUE THREAD

**Issue by ghjp** [Linutronix/elbe#115]
I get the following error if I use the demo file x86_64-pc-hdimg-gnome3.xml

Elbe XML Validation Error
Unknown Exception during validation

If I use xmllint for validation I get:

    xmllint --noout --valid x86_64-pc-hdimg-gnome3.xml

x86_64-pc-hdimg-gnome3.xml:1: validity error : Validation failed: no DTD found !
sion="6" xsi:schemaLocation="https://www.linutronix.de/projects/Elbe dbsfed.xsd"

So what is wrong with the validation here?

**Comment by bene42** [comment]
Your xmllint validation can not perform, because there is no DTD.
The validation pass against a XML schema. Try:
`xmllint --noout --schema https://www.linutronix.de/projects/Elbe/dbsfed.xsd x86_64-pc-hdimg-gnome3.xml`

On my system:
```bash
$ xmllint --noout --schema https://www.linutronix.de/projects/Elbe/dbsfed.xsd x86_64-pc-hdimg-gnome3.xml
x86_64-pc-hdimg-gnome3.xml validates
$
```

Please note that the validation need a valid E.L.B.E. installation, because there is no
accessable file at https://www.linutronix.de/projects/Elbe/dbsfed.xsd.
XML Schema need a namespace. For E.L.B.E. the namespace is
"https://www.linutronix.de/projects/Elbe".

E.L.B.E. installs a XML Catalog for this namespace.
Through the catalog all access to "https://www.linutronix.de/projects/Elbe/dbsfed.xsd"
is redirected to "/usr/share/xml/elbe-common/dbsfed.xsd"

To avoid further confusion the E.L.B.E. XML namespace should be changed to
"urn:ELBE:" and according to this namespace the schema would be referenced by
"urn:ELBE:dbsfed.xsd".
