### ISSUE TITLE
Installing specific package version

### ISSUE THREAD

**Issue by fmg-dave** [Linutronix/elbe#323]
I have a deb repository that has multiple versions of a package. I would like to install a specific version (not the latest) and hold it at that version so that it cannot be updated accidentally.

I currently have an entry in `pkg-list` that looks like this:

`<pkg version="1.2.3">my-package</pkg>`

and an entry in `finetuning` that looks like this:

`<command>apt-mark hold my-package</command>`

However ELBE still installs the latest version of the package and fails validation with the error:

```shell
Package List validation
-----------------------

Package 'my-package' version '1.2.3' does not match installed version 1.5.6
```

I currently get around this by installing the package in `finetuning`:

```
<command>apt-get install my-package=1.2.3</command>
<command>apt-mark hold my-package</command>
```

Does Elbe support this use case? Have I used the `version` attribute incorrectly?

**Comment by martinsteih-lr** [comment]
As I understand the version attribute, it is used for validation only. 
If you structured your repository so that each package version is tied to a release or suite? If so, you could use the pin attribute of pkg (e.g., <pkg pin="mysuite">my-package</pkg>). This way, Elbe would prefer the package's version in mysuite. For all I know, this is the only way to accomplish that.
